version: "2"

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true

linters:
  default: all
  disable:
    - cyclop # duplicate of gocyclo
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - lll
    - mnd
    - nlreturn
    - nonamedreturns
    - paralleltest
    - prealloc
    - rowserrcheck # not relevant (SQL)
    - sqlclosecheck # not relevant (SQL)
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/instana/testify
              desc: not allowed
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    funlen:
      lines: -1
      statements: 40
    goconst:
      min-len: 5
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - sloppyReassign
        - rangeValCopy
        - octalLiteral
        - paramTypeCombine # already handle by gofumpt.extra-rules
      enabled-tags:
        - diagnostic
        - style
        - performance
      settings:
        hugeParam:
          sizeThreshold: 100
    gocyclo:
      min-complexity: 15
    godox:
      keywords:
        - FIXME
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    gosec:
      excludes:
        - G101

  exclusions:
    rules:
      - path: actions.go
        text: (cyclomatic|cognitive) complexity (\d+) of func `\(\*Action\)\.Run` is high
      - path: actions.go
        text: 'Function name: Run, Cyclomatic Complexity: '
      - path: actions.go
        text: Function 'Run' has too many statements
      - path: (.+)\.go$
        text: G101

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
